services:
  db:
    image: postgres:15-alpine
    container_name: pool-workout-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: pool_workouts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pool-workout-server
    environment:
      DATABASE_URL: postgresql://postgres:dbpass@db:5432/pool_workouts
      PORT: 5000
      NODE_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pool-workout-client
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data: